version: '3.8'
services:
  dev-database:
    image: postgres:15.0
    container_name: dev-database
    ports:
      - 5434:5432 # {port in host(myPC)}: {port in Container}
    # environment variables, like db's username, password...
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ThanhNC40@FPT
      POSTGRES_DB: testdb
    networks:
      - nestjs-network
  # Create another service for Testing
  test-database:
    image: postgres:15.0
    container_name: test-database
    ports:
      - 5435:5432 # {port in host(myPC)}: {port in Container}
    # environment variables, like db's username, password...
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ThanhNC40@FPT
      POSTGRES_DB: testdb
    networks:
      - nestjs-network
networks:
  nestjs-network:

# Create container, network,...from "docker compose" file:
# -d: deamon / cbackground mode
# docker compose up -d

# Start specific service
# docker compose up -d dev-database -d

# docker compose down

# How to remove container + image
# docker compose rm dev-database --stop --force --volumes
